export default {
  kind: "youtube#videoListResponse",
  etag: "Ruvk3KbFulUHBoiPjuXjBvYsM_s",
  items: [
    {
      kind: "youtube#video",
      etag: "TIwren3m8ZEt07KewOqtrZNAScw",
      id: "bSkOF-mEbUU",
      snippet: {
        publishedAt: "2023-07-27T18:31:03Z",
        channelId: "UCdbalkQDqCcOsYG5c4L8TAw",
        title:
          "CAPTAIN MILLER -Teaser | Dhanush | Shivarajkumar, Sundeep Kishan, Priyanka Mohan | Arun Matheswaran",
        description:
          "Presenting the Official Teaser of #CaptainMiller . \n\nWritten & Directed by : Arun Matheswaran\nProduced by : Sendhil Thyagarajan & Arjun Thyagarajan\nMusic : GV Prakash\nDOP : Siddhartha Nuni\nDialogues : Madhan Karky\nEditor : Nagooran \nArt Director : T. Ramalingam \nCostume Designing : Poornima Ramasamy & Kavya Sriraam\nStunts :  Dhilip Subbarayan \nPublicity Designer : Tuney John ( 24AM )\nLyrics : Vivek , Arunraja Kamaraj , Umadevi , Kaber Vasuki \nVFX Supervisor: Monesh H\nChoreography: Baskar \nSound design: Sync Cinema \nSound Mixing : MR Rajakrishnan \nPRO : Riaz K Ahmed , Team AIM , Vamsi Sekhar\n\n\nFollow us on \r\nFacebook - https://www.facebook.com/SathyaJyothiFilms/\r\nTwitter - https://www.twitter.com/SathyaJyothi_ \r\nInstagram - https://www.instagram.com/sathyajyothifilms/\r\n\r\nIn Association with Divo\r\nhttps://www.facebook.com/divomovies/\r\nhttps://www.twitter.com/divomovies/\r\nhttps://www.instagram.com/divomovies/\n\n#CaptainMiller #Dhanush #Shivarajkumar #SundeepKishan #PriyankaMohan #GVPrakash #ArunMatheswaran  #sathyaJyothiFilms",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/bSkOF-mEbUU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/bSkOF-mEbUU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/bSkOF-mEbUU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/bSkOF-mEbUU/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/bSkOF-mEbUU/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Sathya Jyothi Films",
        tags: [
          "dhanush",
          "dhanush next movie",
          "dhanush new movie",
          "Captain Miller",
          "captain miller dhanush",
          "sathya jyothi films",
          "dhanush sathya jyothi films",
          "dhanush movies",
          "Arun Matheswaran",
          "gv praksh kumar",
          "gv prakash music director",
          "captain miller Teaser",
          "dhanush captain miller teaser",
          "captain miller Official Teaser",
          "arun matheswaran director",
          "arun matheswaran captain miller",
          "captain miller trailer",
          "Priyanka Mohan",
          "Captain miller dhanush movie teaser",
          "Shivarajkumar Captain miller",
        ],
        categoryId: "1",
        liveBroadcastContent: "none",
        localized: {
          title:
            "CAPTAIN MILLER -Teaser | Dhanush | Shivarajkumar, Sundeep Kishan, Priyanka Mohan | Arun Matheswaran",
          description:
            "Presenting the Official Teaser of #CaptainMiller . \n\nWritten & Directed by : Arun Matheswaran\nProduced by : Sendhil Thyagarajan & Arjun Thyagarajan\nMusic : GV Prakash\nDOP : Siddhartha Nuni\nDialogues : Madhan Karky\nEditor : Nagooran \nArt Director : T. Ramalingam \nCostume Designing : Poornima Ramasamy & Kavya Sriraam\nStunts :  Dhilip Subbarayan \nPublicity Designer : Tuney John ( 24AM )\nLyrics : Vivek , Arunraja Kamaraj , Umadevi , Kaber Vasuki \nVFX Supervisor: Monesh H\nChoreography: Baskar \nSound design: Sync Cinema \nSound Mixing : MR Rajakrishnan \nPRO : Riaz K Ahmed , Team AIM , Vamsi Sekhar\n\n\nFollow us on \r\nFacebook - https://www.facebook.com/SathyaJyothiFilms/\r\nTwitter - https://www.twitter.com/SathyaJyothi_ \r\nInstagram - https://www.instagram.com/sathyajyothifilms/\r\n\r\nIn Association with Divo\r\nhttps://www.facebook.com/divomovies/\r\nhttps://www.twitter.com/divomovies/\r\nhttps://www.instagram.com/divomovies/\n\n#CaptainMiller #Dhanush #Shivarajkumar #SundeepKishan #PriyankaMohan #GVPrakash #ArunMatheswaran  #sathyaJyothiFilms",
        },
        defaultAudioLanguage: "ta",
      },
      contentDetails: {
        duration: "PT1M34S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "13744550",
        likeCount: "378650",
        favoriteCount: "0",
        commentCount: "10364",
      },
    },
    {
      kind: "youtube#video",
      etag: "HkT0gl0ykVO-9o_0GbeqeBeJh9s",
      id: "mljj92tRwlk",
      snippet: {
        publishedAt: "2023-07-26T14:00:13Z",
        channelId: "UC3jMepkLKF8y4iiwWmAB3RA",
        title:
          "#Gadar2 Official Trailer | 11th August | Sunny Deol | Ameesha Patel | Anil Sharma | Zee Studios",
        description:
          "Apne parivaar aur desh ke liye, ek baar phir se Gadar machayega Tara Singh! 💥💪🏻\n\nOn the occasion of #KargilVijayDiwas, presenting you all with #Gadar2Trailer 🔥\n\n#Gadar2 aa rahi hai bade parde par 🔥 lagane iss Independence Day! 🇮🇳 \nCinemas mein 11th August se 🎞️\n\n#SunnyDeol #AmeeshaPatel #AnilSharma #ZeeStudios \n\nGet 1+1 on Movie Tickets - https://m.paytm.me/dl_gadar2\n\nZee Studios Presents\nDirected by - Anil Sharma\nProduced by - Zee Studios\nProduced by - Anil Sharma Productions, MM Moviez \nCo-Producer - Suman Sharma\n\nStarring -\nSunny Deol\nAmeesha Patel \nUtkarsh Sharma\nManish Wadhwa\nGaurav Chopra\nLuv Sinha\nIntroducing - Simrat Kaur\n\nWritten by - Shaktimaan Talwar\nCinematographer - Najeeb Khan\nMusic - Mithoon\nLyricist - Sayeed Quadri\nChoreography - Shabina Khan\nProduction Desginer - Muneesh Sappel\nCostumes Stylists - Nidhi Yasha, Gagan Oberoi (Sunny Deol)\n\nAction Directors - \nRavi Verma, Tinu Verma, Shyam Kaushal & Abbas Ali Moghul\nBackground Music - Monty Sharma\nEditor - Ashfaq Makrani & Sanjay Sankhla\nSound Designer - Jitendra Chaudhry \nMixing - Anup Dev\nExecutive Producer - Rana Bhatia\nSound Designer (SFX) - Kingshuk Moran\nSecond Unit Cameraman - Azeez Siddiqui\n\nAssociate Directors - Hidayat Khan & Hanish Lamba\n\nVFX - Pixelld Studios, Prisca \n\nDi - Prime Focus \nColorist - Ashirwaad \n\nVisual Promotions - MA+TH (Marching Ants+ Trigger Happy) •Member of Hakuhodo International•\n\nPoster Design - Rahul Nanda \n\n\nStay Updated On:\nhttps://www.facebook.com/ZeeStudios​\nhttps://twitter.com/ZeeStudios_​\nhttps://www.instagram.com/zeestudiosofficial/\nhttps://www.youtube.com/ZeeStudiosofficial",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/mljj92tRwlk/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/mljj92tRwlk/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/mljj92tRwlk/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/mljj92tRwlk/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/mljj92tRwlk/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Zee Studios",
        tags: [
          "Zee Studios",
          "Bollywood Cinema",
          "Hindi Cinema",
          "Bollywood movie",
          "Latest bollywood movie",
          "Gadar 2 upcoming bollywood movie",
          "Trailer",
          "zee",
          "entertainment",
          "popular",
          "famous",
          "superhit",
          "Blockbuster movie",
          "Sunny Deol",
          "Ameesha Patel",
          "Sunny Deol Movie Gadar 2",
          "Gadar 2 Teaser",
          "Gadar 2 Trailer",
          "Sunny Deol Action",
          "Hindustan Zindadabad",
          "Sakeena",
          "Tara Singh",
          "Utkarsh Sharma",
          "Anil Sharma",
          "Latest 2023 Trailer",
        ],
        categoryId: "1",
        liveBroadcastContent: "none",
        localized: {
          title:
            "#Gadar2 Official Trailer | 11th August | Sunny Deol | Ameesha Patel | Anil Sharma | Zee Studios",
          description:
            "Apne parivaar aur desh ke liye, ek baar phir se Gadar machayega Tara Singh! 💥💪🏻\n\nOn the occasion of #KargilVijayDiwas, presenting you all with #Gadar2Trailer 🔥\n\n#Gadar2 aa rahi hai bade parde par 🔥 lagane iss Independence Day! 🇮🇳 \nCinemas mein 11th August se 🎞️\n\n#SunnyDeol #AmeeshaPatel #AnilSharma #ZeeStudios \n\nGet 1+1 on Movie Tickets - https://m.paytm.me/dl_gadar2\n\nZee Studios Presents\nDirected by - Anil Sharma\nProduced by - Zee Studios\nProduced by - Anil Sharma Productions, MM Moviez \nCo-Producer - Suman Sharma\n\nStarring -\nSunny Deol\nAmeesha Patel \nUtkarsh Sharma\nManish Wadhwa\nGaurav Chopra\nLuv Sinha\nIntroducing - Simrat Kaur\n\nWritten by - Shaktimaan Talwar\nCinematographer - Najeeb Khan\nMusic - Mithoon\nLyricist - Sayeed Quadri\nChoreography - Shabina Khan\nProduction Desginer - Muneesh Sappel\nCostumes Stylists - Nidhi Yasha, Gagan Oberoi (Sunny Deol)\n\nAction Directors - \nRavi Verma, Tinu Verma, Shyam Kaushal & Abbas Ali Moghul\nBackground Music - Monty Sharma\nEditor - Ashfaq Makrani & Sanjay Sankhla\nSound Designer - Jitendra Chaudhry \nMixing - Anup Dev\nExecutive Producer - Rana Bhatia\nSound Designer (SFX) - Kingshuk Moran\nSecond Unit Cameraman - Azeez Siddiqui\n\nAssociate Directors - Hidayat Khan & Hanish Lamba\n\nVFX - Pixelld Studios, Prisca \n\nDi - Prime Focus \nColorist - Ashirwaad \n\nVisual Promotions - MA+TH (Marching Ants+ Trigger Happy) •Member of Hakuhodo International•\n\nPoster Design - Rahul Nanda \n\n\nStay Updated On:\nhttps://www.facebook.com/ZeeStudios​\nhttps://twitter.com/ZeeStudios_​\nhttps://www.instagram.com/zeestudiosofficial/\nhttps://www.youtube.com/ZeeStudiosofficial",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT3M3S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "51494286",
        likeCount: "921099",
        favoriteCount: "0",
        commentCount: "77068",
      },
    },
    {
      kind: "youtube#video",
      etag: "B4lr5hlUMYfr91yB54sGjh8JNfI",
      id: "W3EC1fx1Yqg",
      snippet: {
        publishedAt: "2023-07-27T10:35:33Z",
        channelId: "UCu1cFPQalIQlHHDSxn_PI0w",
        title:
          "Bholaa Shankar Trailer | MegaStar Chiranjeevi,Keerthy Suresh Tamannaah | Meher Ramesh | Anil Sunkara",
        description:
          "Watch Bholaa Shankar Trailer\n\n#BholaaShankar Starring Chiranjeevi, Tamannaah, Keerthy Suresh, Sushanth, Raghu Babu, Murali Sharma, Ravi Shankar, Vennela Kishore, Tulasi, Sri Mukhi, Bithiri Sathi, Satya, Getup Srinu, Rashmi Gautam, Uttej, etc.\n\nMovie :- BholaaShankar\nDirector: Meher Ramesh\nProducer: Ramabrahmam Sunkara\nBanner: AK Entertainments\nCo Producer's - Anil Sunkara, Ajay Sunkara\nEx-Producer: Kishore Garikipati\nMusic: Mahati Swara Sagar\nDOP: Dudley\nEditor: Marthand K Venkatesh\nProduction Designer: AS Prakash\nFight Masters: Ram-Laxman\nChoreography: Sekhar Master\nDialogues: Mamidala Thirupathi\nLyrics: Ramajogayya Sastry, Kasarla Shyam,Meher Ramesh\nVFX supervisor - Yugandhar T\nDigital Marketing - Viswa CM\nPRO - Vamsi Shekar\n\nAP BOOK:  Most Trusted Telugu Betbook \nOnline Gaming Platform Cricket,Football,Tennis,Casino,Ludo  \n\nRegister now AP BOOK\nhttps://apbook.in/  Contact : 7038888888\n\n\nFollow Us on Social Media:-\r\nFacebook - https://www.facebook.com/AKentsOfficial/\r\nTwitter - https://twitter.com/akentsofficial\r\nInstagram - https://instagram.com/akentsofficial/",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/W3EC1fx1Yqg/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/W3EC1fx1Yqg/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/W3EC1fx1Yqg/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/W3EC1fx1Yqg/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/W3EC1fx1Yqg/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "AK Entertainments",
        tags: [
          "Bholaa Shankar Trailer",
          "Bholaa Shankar Teaser",
          "megastar chiranjeevi",
          "chiranjeevi",
          "chiranjeevi bhola shankar",
          "bhola shankar teaser",
          "bhola shankar trailer",
          "bhola shankar",
          "ak entertainments",
          "meher ramesh",
          "bholaa",
        ],
        categoryId: "1",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Bholaa Shankar Trailer | MegaStar Chiranjeevi,Keerthy Suresh Tamannaah | Meher Ramesh | Anil Sunkara",
          description:
            "Watch Bholaa Shankar Trailer\n\n#BholaaShankar Starring Chiranjeevi, Tamannaah, Keerthy Suresh, Sushanth, Raghu Babu, Murali Sharma, Ravi Shankar, Vennela Kishore, Tulasi, Sri Mukhi, Bithiri Sathi, Satya, Getup Srinu, Rashmi Gautam, Uttej, etc.\n\nMovie :- BholaaShankar\nDirector: Meher Ramesh\nProducer: Ramabrahmam Sunkara\nBanner: AK Entertainments\nCo Producer's - Anil Sunkara, Ajay Sunkara\nEx-Producer: Kishore Garikipati\nMusic: Mahati Swara Sagar\nDOP: Dudley\nEditor: Marthand K Venkatesh\nProduction Designer: AS Prakash\nFight Masters: Ram-Laxman\nChoreography: Sekhar Master\nDialogues: Mamidala Thirupathi\nLyrics: Ramajogayya Sastry, Kasarla Shyam,Meher Ramesh\nVFX supervisor - Yugandhar T\nDigital Marketing - Viswa CM\nPRO - Vamsi Shekar\n\nAP BOOK:  Most Trusted Telugu Betbook \nOnline Gaming Platform Cricket,Football,Tennis,Casino,Ludo  \n\nRegister now AP BOOK\nhttps://apbook.in/  Contact : 7038888888\n\n\nFollow Us on Social Media:-\r\nFacebook - https://www.facebook.com/AKentsOfficial/\r\nTwitter - https://twitter.com/akentsofficial\r\nInstagram - https://instagram.com/akentsofficial/",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT2M26S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "11838118",
        likeCount: "261271",
        favoriteCount: "0",
        commentCount: "7786",
      },
    },
    {
      kind: "youtube#video",
      etag: "1btpnGwQp7JQBzrlYvenjToW8tY",
      id: "UfrT9zkwqDU",
      snippet: {
        publishedAt: "2023-07-26T10:35:02Z",
        channelId: "UCNApqoVYJbYSrni4YsbXzyQ",
        title:
          "Ticket Eh Konakunda Lyrical Song | Tillu Square | Siddu, Anupama | Mallik Ram | Ram Miriyala",
        description:
          '#AdityaMusic Presents Ticket Eh Konakunda Lyrical Song  From The Movie #Tillusquare \n\n#TilluSquare is our upcoming Telugu feature film Strarring Siddu Jonnalagadda, Anupama Parameswaran in lead roles. Directed by Mallik Ram. Music composed by Ram Miriyala & Sri Charan Pakala. Editing by Navin Nooli. Cinematography by Sai Prakash. Produced by Suryadevara Naga Vamsi Under Sithara Entertainments & Fortune Four Cinemas. Presented by Srikara Studios\n\nSong Name: Ticket Eh Konakunda\nSinger:  Ram Miriyala\nLyrics: Kasarla Shyam\nMusic: Ram Miriyala\nArranged & Programmed by Ram Miriyala, Shashank Alamuru & Arun Chiluveru\nAcoustic Guitars by Arun Chiluveru\nKeyboards by Shashank Alamuru & Arun Chiluveru \nRhythm Programmed by Ram Miriyala\nAdditional Vocals: Akash Ravuru\nMixing & Mastering By Vinay Kumar\n\n\nMovie Name: Tillu Square\nDirector : Mallik Ram \nDOP: Sai Prakash Ummadisingu\nEditor : Navin Nooli \nMusic Director: Ram Miryala, Sri Charan Pakala  \nArt: A.S. Prakash\nProducer: Suryadevara Naga Vamsi\nBanner: Sithara Entertainments, Fortune Four Cinemas\nPresenter: Srikara Studios\nAudio: Aditya Music\n \n#TicketEhKonakundaSong #SiddhuJonnalagadda  #AnupamaParameswaran  #RamMiriyala #KasrlaShyam #DjTillu2\n------------------------------------------------------------------------------------------\nEnjoy and stay connected with us!!\n►Subscribe us on Youtube: http://bit.ly/adityamusic\n►Like us on Facebook: http://www.facebook.com/adityamusic\n►Follow us on Twitter: http://www.twitter.com/adityamusic\n►Follow us on Instagram: https://www.instagram.com/adityamusicindia\n►Follow us on LinkedIn: http://bit.ly/2Pp6ze3\n\nSUBSCRIBE Aditya Music Channels for unlimited entertainment:\n►For South Indian Dubbed Movies in HD: http://www.youtube.com/Adityamovies\n►For Songs with Telugu Lyrics: https://bit.ly/3cpQuFH\n►For Devotional Songs: http://www.youtube.com/AdityaDevotional\n\n\n→"మా పాట మీ నోట" Telugu Lyrical Songs https://www.youtube.com/@mapaatameenota\n→Latest Tollywood Lyric Video Songs - http://bit.ly/1Km97mg\n→Ever Green Classics - https://goo.gl/1fZEDy\n→Popular Jukeboxes - https://goo.gl/LNvAIo\n→Telugu Songs with Lyrics - https://goo.gl/7ZmgWT\n\n© 2023 Aditya Music India Pvt. Ltd.',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/UfrT9zkwqDU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/UfrT9zkwqDU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/UfrT9zkwqDU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/UfrT9zkwqDU/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/UfrT9zkwqDU/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Aditya Music India",
        tags: [
          "Ticket Eh Konakunda Lyrical Song",
          "Siddhu Jonnalagadda",
          "Anupama Parameswaran",
          "Mallik Ram",
          "S Naga Vamsi",
          "Tillu Square Movie",
          "Tillu Square 1st Single",
          "Tillu Square Telugu Movie",
          "Tillu Square Teaser",
          "DJ Tillu 2 First Look",
          "Star Boy Siddu",
          "DJ Tillu 2",
          "Siddu's Tillu Square",
          "Siddu in DJ Tillu 2",
          "Ram Miryala Music",
          "Ram Miryala Songs",
          "Siddhu Jonnalagadda Latest Movie",
          "Anupama Parameswaran Telugu Moives",
          "Kalsarla Shyam",
          "Tillu Square Song Promo",
          "Tillu Anna Dj Pedithe",
          "Dj Tillu Songs",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Ticket Eh Konakunda Lyrical Song | Tillu Square | Siddu, Anupama | Mallik Ram | Ram Miriyala",
          description:
            '#AdityaMusic Presents Ticket Eh Konakunda Lyrical Song  From The Movie #Tillusquare \n\n#TilluSquare is our upcoming Telugu feature film Strarring Siddu Jonnalagadda, Anupama Parameswaran in lead roles. Directed by Mallik Ram. Music composed by Ram Miriyala & Sri Charan Pakala. Editing by Navin Nooli. Cinematography by Sai Prakash. Produced by Suryadevara Naga Vamsi Under Sithara Entertainments & Fortune Four Cinemas. Presented by Srikara Studios\n\nSong Name: Ticket Eh Konakunda\nSinger:  Ram Miriyala\nLyrics: Kasarla Shyam\nMusic: Ram Miriyala\nArranged & Programmed by Ram Miriyala, Shashank Alamuru & Arun Chiluveru\nAcoustic Guitars by Arun Chiluveru\nKeyboards by Shashank Alamuru & Arun Chiluveru \nRhythm Programmed by Ram Miriyala\nAdditional Vocals: Akash Ravuru\nMixing & Mastering By Vinay Kumar\n\n\nMovie Name: Tillu Square\nDirector : Mallik Ram \nDOP: Sai Prakash Ummadisingu\nEditor : Navin Nooli \nMusic Director: Ram Miryala, Sri Charan Pakala  \nArt: A.S. Prakash\nProducer: Suryadevara Naga Vamsi\nBanner: Sithara Entertainments, Fortune Four Cinemas\nPresenter: Srikara Studios\nAudio: Aditya Music\n \n#TicketEhKonakundaSong #SiddhuJonnalagadda  #AnupamaParameswaran  #RamMiriyala #KasrlaShyam #DjTillu2\n------------------------------------------------------------------------------------------\nEnjoy and stay connected with us!!\n►Subscribe us on Youtube: http://bit.ly/adityamusic\n►Like us on Facebook: http://www.facebook.com/adityamusic\n►Follow us on Twitter: http://www.twitter.com/adityamusic\n►Follow us on Instagram: https://www.instagram.com/adityamusicindia\n►Follow us on LinkedIn: http://bit.ly/2Pp6ze3\n\nSUBSCRIBE Aditya Music Channels for unlimited entertainment:\n►For South Indian Dubbed Movies in HD: http://www.youtube.com/Adityamovies\n►For Songs with Telugu Lyrics: https://bit.ly/3cpQuFH\n►For Devotional Songs: http://www.youtube.com/AdityaDevotional\n\n\n→"మా పాట మీ నోట" Telugu Lyrical Songs https://www.youtube.com/@mapaatameenota\n→Latest Tollywood Lyric Video Songs - http://bit.ly/1Km97mg\n→Ever Green Classics - https://goo.gl/1fZEDy\n→Popular Jukeboxes - https://goo.gl/LNvAIo\n→Telugu Songs with Lyrics - https://goo.gl/7ZmgWT\n\n© 2023 Aditya Music India Pvt. Ltd.',
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT4M6S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "4737075",
        likeCount: "233039",
        favoriteCount: "0",
        commentCount: "3374",
      },
    },
    {
      kind: "youtube#video",
      etag: "cjicuI97JHBRDlgMxaKQ_ka3Dp8",
      id: "L2AFfVPwikY",
      snippet: {
        publishedAt: "2023-07-27T09:27:23Z",
        channelId: "UCKKsaW4uKAV7yhywGaoj6eg",
        title: "Abhijeet Ki Shadi Ep. 624 | FUNwithPRASAD | #funwithprasad",
        description:
          "CREDITS\n\nAll Characters Played By - Prasad\n\nMusic By - https://youtube.com/channel/UCRRaev1HM8OTkIiKBGo1w5A\nhttps://mobcup.net/\nved prajapati\nvasanth isaipettai\nAll Songs Credit Gose To Official Song Owners\n\nVideo Editing By - Prasad\n\nHope So You Like This\n\nSmile On Face This Is Only Reason Behind This\nThank You So Much For Watching",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/L2AFfVPwikY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/L2AFfVPwikY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/L2AFfVPwikY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/L2AFfVPwikY/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/L2AFfVPwikY/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "FUNwithPRASAD",
        tags: [
          "funwithprasad",
          "funwithprasad new video",
          "fun with prasad comedy",
          "fun with prasad",
          "fun with prasad new video",
          "funwithprasad comedy",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title: "Abhijeet Ki Shadi Ep. 624 | FUNwithPRASAD | #funwithprasad",
          description:
            "CREDITS\n\nAll Characters Played By - Prasad\n\nMusic By - https://youtube.com/channel/UCRRaev1HM8OTkIiKBGo1w5A\nhttps://mobcup.net/\nved prajapati\nvasanth isaipettai\nAll Songs Credit Gose To Official Song Owners\n\nVideo Editing By - Prasad\n\nHope So You Like This\n\nSmile On Face This Is Only Reason Behind This\nThank You So Much For Watching",
        },
        defaultAudioLanguage: "en-IN",
      },
      contentDetails: {
        duration: "PT30M20S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        regionRestriction: {
          blocked: ["RU"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "817257",
        likeCount: "61417",
        favoriteCount: "0",
        commentCount: "14622",
      },
    },
    {
      kind: "youtube#video",
      etag: "eUb7bXCXfAYIj0FjOxaSN7ZGig4",
      id: "xelrmlSG_2c",
      snippet: {
        publishedAt: "2023-07-27T15:00:43Z",
        channelId: "UCpEhnqL0y41EpW2TvWAHD7Q",
        title:
          "NEW! Barsatein - Mausam Pyar Ka - Ep 14 | 27 July 2023 | Teaser",
        description:
          "Click here to Subscribe to SET India: https://www.youtube.com/channel/UCpEhnqL0y41EpW2TvWAHD7Q?sub_confirmation=1\n\nEpisode 14:  Reyansh का प्यार\n-----------------------------------------------------------------\nAs Reyansh is all shattered seeing the relationship between his parents in the family, so he gets drunk and then Aradhana turns up and takes care of him. She takes him to the office and takes good care of him, they both spend the night together. Now, Stay Tuned to know how will Reyansh express his deep hidden feelings to Aradhana and what will be her ultimate reaction to it.\n\n\nShow Name: Barsatein - Mausam Pyaar Ka\nCast: Shivangi Joshi, Kushal Tandon\nEpisode: 14\nDirector: Atif Khan\nProducer: Ekta Kapoor\n\n#barsateinmausampyaarka #setindia #बरसातेंमौसमप्यारका #kushaltandon #shivangijoshi \n\n\nAbout Barsatein - Mausam Pyaar Kaa:\n------------------------------------------------------------\nA sensible and ambitious journalist joins a media company run by a suave maverick man. While united in their passion for honest and ground-breaking journalism, their contrasting characters immediately puts them at loggerheads. What will happen when she starts falling in love with him despite the red flags? 'Barsatein - Mausam Pyaar Ka' stars Shivangi Joshi and Kushal Tandon in lead roles.\n\nClick here to watch the full episode of Barsatein - Mausam Pyaar Ka:\nhttps://www.sonyliv.com/dplnk?schema=sony://asset/1000229285\n\nNEW! Barsatein - Mausam Pyar Ka - Ep 14 | 27 July 2023 | Teaser",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/xelrmlSG_2c/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/xelrmlSG_2c/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/xelrmlSG_2c/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/xelrmlSG_2c/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/xelrmlSG_2c/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "SET India",
        tags: [
          "Shivangi Joshi",
          "Barsatein serial",
          "hindi tv show",
          "बरसातें",
          "Barsatein story",
          "new story",
          "set india",
          "hindi tv serials",
          "Barsatein new",
          "barsatein",
          "barsatein serial",
          "barsatein shivangi joshi",
          "barsatein serial new",
          "barsaatein new show online",
          "barsaatein",
          "barsatein new",
          "barsaatein story",
          "barsatein star cast",
          "barsatein new show",
          "ekta kapoor barsatein",
          "sony tv show barsaatein",
          "barsatein mausam pyaar ka ep 14",
          "teaser",
          "barsatein teaser",
          "Barsatein kushal tandon",
          "barsatein today episode",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title:
            "NEW! Barsatein - Mausam Pyar Ka - Ep 14 | 27 July 2023 | Teaser",
          description:
            "Click here to Subscribe to SET India: https://www.youtube.com/channel/UCpEhnqL0y41EpW2TvWAHD7Q?sub_confirmation=1\n\nEpisode 14:  Reyansh का प्यार\n-----------------------------------------------------------------\nAs Reyansh is all shattered seeing the relationship between his parents in the family, so he gets drunk and then Aradhana turns up and takes care of him. She takes him to the office and takes good care of him, they both spend the night together. Now, Stay Tuned to know how will Reyansh express his deep hidden feelings to Aradhana and what will be her ultimate reaction to it.\n\n\nShow Name: Barsatein - Mausam Pyaar Ka\nCast: Shivangi Joshi, Kushal Tandon\nEpisode: 14\nDirector: Atif Khan\nProducer: Ekta Kapoor\n\n#barsateinmausampyaarka #setindia #बरसातेंमौसमप्यारका #kushaltandon #shivangijoshi \n\n\nAbout Barsatein - Mausam Pyaar Kaa:\n------------------------------------------------------------\nA sensible and ambitious journalist joins a media company run by a suave maverick man. While united in their passion for honest and ground-breaking journalism, their contrasting characters immediately puts them at loggerheads. What will happen when she starts falling in love with him despite the red flags? 'Barsatein - Mausam Pyaar Ka' stars Shivangi Joshi and Kushal Tandon in lead roles.\n\nClick here to watch the full episode of Barsatein - Mausam Pyaar Ka:\nhttps://www.sonyliv.com/dplnk?schema=sony://asset/1000229285\n\nNEW! Barsatein - Mausam Pyar Ka - Ep 14 | 27 July 2023 | Teaser",
        },
        defaultAudioLanguage: "hi",
      },
      contentDetails: {
        duration: "PT10M42S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        regionRestriction: {
          allowed: ["IN", "PK"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1543338",
        likeCount: "29617",
        favoriteCount: "0",
        commentCount: "929",
      },
    },
    {
      kind: "youtube#video",
      etag: "xnPcNGzntnD7R0j50buBwrSfRnU",
      id: "kw66jiCoxZA",
      snippet: {
        publishedAt: "2023-07-27T04:28:44Z",
        channelId: "UC4U5j8zZxVT9xYfXSDKN7aQ",
        title:
          "A Relaxed & Enjoyable Day After A Munnar Trip 🥰 | Bhabi’s Special Fish Biriyani & Prawns Fry 😋",
        description:
          "BB1988 Step Into Style Instagram - https://instagram.com/bb1988__stepintostyle?igshid=YmMyMTA2M2Y=\n\nBB1988 Step Into Style YouTube - https://youtube.com/@BB1988StepIntoStyle\n\nPlease check catalog & price on WhatsApp: https://wa.me/c/919995916104\n\nBB1988 Cosmetics:-\n\n1) BB BORNA SKIN BRIGHTENING CREAM\n\nShop now 👇\n\nhttps://wa.me/p/6386882754662211/918089680298\n\n2) BB BORNA BEARD OIL\n\nShop now 👇\n\nhttps://wa.me/p/5226451670793499/918089680298\n\n3) BB1988 HAIR & BEARD CARE OIL\n\nShop now 👇\n\nhttps://wa.me/p/9129124410446895/918089680298\n\n4) BB1988 HANDCRAFTED ORGANIC SOAP\n\nShop now 👇\n\nOrder Now  - 8089680298\n\nBB1988 Cosmetics Instagram - https://instagram.com/bb1988_cosmetics\n\nFacebook  - https://www.facebook.com/bb1988cosmetics\n\n🛍 Online shop now - www.bb1988cosmetics.com",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/kw66jiCoxZA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/kw66jiCoxZA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/kw66jiCoxZA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/kw66jiCoxZA/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/kw66jiCoxZA/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Suhana Basheer",
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title:
            "A Relaxed & Enjoyable Day After A Munnar Trip 🥰 | Bhabi’s Special Fish Biriyani & Prawns Fry 😋",
          description:
            "BB1988 Step Into Style Instagram - https://instagram.com/bb1988__stepintostyle?igshid=YmMyMTA2M2Y=\n\nBB1988 Step Into Style YouTube - https://youtube.com/@BB1988StepIntoStyle\n\nPlease check catalog & price on WhatsApp: https://wa.me/c/919995916104\n\nBB1988 Cosmetics:-\n\n1) BB BORNA SKIN BRIGHTENING CREAM\n\nShop now 👇\n\nhttps://wa.me/p/6386882754662211/918089680298\n\n2) BB BORNA BEARD OIL\n\nShop now 👇\n\nhttps://wa.me/p/5226451670793499/918089680298\n\n3) BB1988 HAIR & BEARD CARE OIL\n\nShop now 👇\n\nhttps://wa.me/p/9129124410446895/918089680298\n\n4) BB1988 HANDCRAFTED ORGANIC SOAP\n\nShop now 👇\n\nOrder Now  - 8089680298\n\nBB1988 Cosmetics Instagram - https://instagram.com/bb1988_cosmetics\n\nFacebook  - https://www.facebook.com/bb1988cosmetics\n\n🛍 Online shop now - www.bb1988cosmetics.com",
        },
      },
      contentDetails: {
        duration: "PT38M58S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "233024",
        likeCount: "8216",
        favoriteCount: "0",
        commentCount: "194",
      },
    },
    {
      kind: "youtube#video",
      etag: "e-7j1Dy_M9NlsiZGtWtuWyY5i6k",
      id: "csHj3WSs980",
      snippet: {
        publishedAt: "2023-07-25T14:16:22Z",
        channelId: "UCjNgqJ_FMLntYVzq7daw1TQ",
        title: "This is my Village in Haryana!",
        description:
          "I visit my village and the city where I was born - Rohtak in Haryana. \n\n🤖 Join my AI Course: https://academy.dhruvrathee.com/chatgpt\nLearn to harness the power of ChatGPT effectively and transform your life! \nUse coupon code: HOME45 for 45% discount! \nHurry up! Offer only valid for the first 400 people\n\n✏️ Join my Time Management Course: https://academy.dhruvrathee.com Are you curious about how I manage to travel so much and still stay productive? Learn how to manage time and maximize productivity in my specialised online course. Use GET20 for a straight up 20% discount!\n\nINSTAGRAM:\n🙋🏼‍♀️ Follow Juli: https://instagram.com/juli_lbr\n🙋🏻‍♂️ Follow Dhruv: http://www.instagram.com/dhruvrathee \n\nYOUTUBE CHANNELS:\n▶️ Main Channel: http://www.youtube.com/dhruvrathee \n🎦 Vlog Channel: http://www.youtube.com/dhruvratheevlogs\n🩳 Shorts Channel: https://www.youtube.com/channel/UCw4IHIMsDO5wpIiprOSXiEA\n\nLISTEN TO MY PODCAST: \n🎧 My Spotify exclusive podcast. Learn about how India works, only on Maha Bharat with Dhruv Rathee: https://spoti.fi/3IhBW51\n----------------------------------------------------",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/csHj3WSs980/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/csHj3WSs980/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/csHj3WSs980/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/csHj3WSs980/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/csHj3WSs980/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Dhruv Rathee Vlogs",
        tags: [
          "Dhruv rathee",
          "Dhruv Rathee vlogs",
          "Dhruv Rathee vlog",
          "vlog",
          "Dhruv Rathee girlfriend",
          "dhruv",
          "rathee",
          "travel",
          "travel vlog",
          "indian vlogger",
          "flying beast",
          "carryminati",
          "best places to travel",
          "Europe travel",
          "Europe trip",
          "Tourism",
          "haryana",
          "village",
          "india",
          "india tourism",
          "rohtak",
          "Dhruv Rathee village",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "This is my Village in Haryana!",
          description:
            "I visit my village and the city where I was born - Rohtak in Haryana. \n\n🤖 Join my AI Course: https://academy.dhruvrathee.com/chatgpt\nLearn to harness the power of ChatGPT effectively and transform your life! \nUse coupon code: HOME45 for 45% discount! \nHurry up! Offer only valid for the first 400 people\n\n✏️ Join my Time Management Course: https://academy.dhruvrathee.com Are you curious about how I manage to travel so much and still stay productive? Learn how to manage time and maximize productivity in my specialised online course. Use GET20 for a straight up 20% discount!\n\nINSTAGRAM:\n🙋🏼‍♀️ Follow Juli: https://instagram.com/juli_lbr\n🙋🏻‍♂️ Follow Dhruv: http://www.instagram.com/dhruvrathee \n\nYOUTUBE CHANNELS:\n▶️ Main Channel: http://www.youtube.com/dhruvrathee \n🎦 Vlog Channel: http://www.youtube.com/dhruvratheevlogs\n🩳 Shorts Channel: https://www.youtube.com/channel/UCw4IHIMsDO5wpIiprOSXiEA\n\nLISTEN TO MY PODCAST: \n🎧 My Spotify exclusive podcast. Learn about how India works, only on Maha Bharat with Dhruv Rathee: https://spoti.fi/3IhBW51\n----------------------------------------------------",
        },
        defaultAudioLanguage: "hi",
      },
      contentDetails: {
        duration: "PT12M17S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2331937",
        likeCount: "91478",
        favoriteCount: "0",
        commentCount: "6845",
      },
    },
    {
      kind: "youtube#video",
      etag: "tZ6zhge834cAaaAq-FXdimvW7vE",
      id: "wUb2VtDdWj0",
      snippet: {
        publishedAt: "2023-07-26T16:01:11Z",
        channelId: "UC2kBDwkqiy7zgH1-M4UtUXQ",
        title: "Ruhaan ka pyara sa gift❤️ | My new routine🙈",
        description:
          "#dipikakiduniya #shoaika \n\nMusic: Pixels\nMusician: Jeff Kaale",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/wUb2VtDdWj0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/wUb2VtDdWj0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/wUb2VtDdWj0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/wUb2VtDdWj0/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/wUb2VtDdWj0/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Dipika Ki Duniya",
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "Ruhaan ka pyara sa gift❤️ | My new routine🙈",
          description:
            "#dipikakiduniya #shoaika \n\nMusic: Pixels\nMusician: Jeff Kaale",
        },
      },
      contentDetails: {
        duration: "PT13M12S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1876898",
        likeCount: "103599",
        favoriteCount: "0",
        commentCount: "3849",
      },
    },
    {
      kind: "youtube#video",
      etag: "574HK4lOF9Vog8DO4hHWnsQJGjA",
      id: "NU7xtlIeyFA",
      snippet: {
        publishedAt: "2023-07-27T12:31:10Z",
        channelId: "UC68nKdrLbLL0Vj7ilVkLmmg",
        title:
          "Kushi - Title Song (Promo) | Vijay Deverakonda, Samantha | Hesham Abdul Wahab | Shiva Nirvana",
        description:
          "Here is 'the most awaited 'Kushi - Title Song promo  starring Vijay Deverakonda, Samantha & Others. A Shiva Nirvana Entertainer. A Hesham Abdul Wahab Musical.\n\nKUSHI TITLE SONG TELUGU\nMusic Composed, Arranged & Programmed by Hesham Abdul Wahab\nLyrics by Shiva Nirvana\nSung by Hesham Abdul Wahab\nChoreographer Brindha Master\n\nMusician Credits: \n\nSaaz & Oud: Tapas Roy\nBass Guitar: Sumesh Parameswar\nMridangam: D.A Srinivas \nStrings: Chennai Strings\n\nMusic Assistants: Suroor Musthafa & George Thomas PV\nArtist Co-ordination: K.D Vincent & Don Vincent\n\nSong Mixed and Mastered by\nEric Pillai (Future Sound Of Bombay)\n\nRecording Engineers:\nSuroor Musthafa  @HW Studio (Cochin)\nGeorge Thomas PV @HW Studio (Cochin) \nBiju James @UNO Records (Chennai)\nNaresh Mamindla @Jubilee10 Studios (Hyderabad)\nRakesh Mikky @Jubilee10 Studios (Hyderabad)\nMidhun Manoj @Soundtown Studios (Chennai)\nVishnu Shankar @Soundtown Studios (Chennai)\nRahul @Studio504 (Mumbai)\n\n\nAudio Recording Studios:\nHW Studio (Cochin)\nUNO Records (Chennai)\nJubilee10 Studios (Hyderabad)\nSoundtown Studios (Chennai) \nStudio504 (Mumbai)\n\nCast - Vijay Deverakonda, Samantha Ruth Prabhu, Jayaram, Sachin Khedakar, Murali Sharma, Lakshmi, Ali, Rohini, Vennela Kishore, Rahul Ramakrishna, Srikanth Iyengar and Saranya Pradeep\n\nTechnical Crew:\nMake Up : Basha\nCostumes : P.Venkat\nStylist: Rajesh\nProduction Executive: Denkala RamaKrishna \nProduction Controller: Shaik Shekshavali \nArt Directors : Uttara kumar Surisetty, Chandrika\nStunts : Peter Hein, V.Venkat \nChoreography: Choreography: Raju Sundaram, Brinda, Pony Verma\nP.R.O : GSK Media\nWriting Assistance : Naresh babu.P\nPublicity Designer: Kabilan\nCo-Director: Suresh kumar\nProduction Designer: Jayashree Lakshminarayanan\nExecutive Producer : Dinesh Narasimhan\nEditing : Prawin Pudi\nMusic : Hesham Abdul Wahab\nD.O.P : G.Murali\nC.E.O : Cherry\nMarketing : First Show\n\nD.I & SOUND MIX : ANNAPURNA STUDIOS \nVFX : MATRIX\nPRODUCERS : NAVEEN YERNENI RAVI SHANKAR YELAMANCHILI \nSTORY - SCREENPLAY - DIALOGUES - DIRECTION : SHIVA NIRVANA\n\nLabel: Saregama India Limited, A RPSG Group Company\n\nTo buy Carvaan, visit https://www.saregama.com/carvaan/telugu\nTo buy virus free original tracks, visit  https://www.saregama.com/musicstore\nFollow us on: YouTube:https://www.youtube.com/channel/saregamatelugu\nFacebook: http://www.facebook.com/Saregamatelugu\nTwitter: https://twitter.com/saregamasouth​​\n\n#KushiTitleSong #VijayDeverakonda #Samantha #SaregamaTelugu",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/NU7xtlIeyFA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/NU7xtlIeyFA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/NU7xtlIeyFA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/NU7xtlIeyFA/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/NU7xtlIeyFA/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Saregama Telugu",
        tags: [
          "kushi title song",
          "kushi song",
          "Vijay Devarakonda",
          "Samantha",
          "kushi",
          "kushi songs",
          "aaradhya song kushi",
          "kushi telugu songs",
          "kushi second single",
          "kushi vijay devarakonda",
          "kushi samantha",
          "latest telugu songs",
          "kushi telugu single",
          "vijay devarakonda songs",
          "vijay devarakonda new movie",
          "kushi song promo",
          "Kushi songs",
          "samantha",
          "vijay devarakonda kushi movie",
          "samantha ruth prabhu",
          "telugu love songs",
          "Aradhya song promo",
          "trending songs telugu",
          "Telugu Love songs",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title:
            "Kushi - Title Song (Promo) | Vijay Deverakonda, Samantha | Hesham Abdul Wahab | Shiva Nirvana",
          description:
            "Here is 'the most awaited 'Kushi - Title Song promo  starring Vijay Deverakonda, Samantha & Others. A Shiva Nirvana Entertainer. A Hesham Abdul Wahab Musical.\n\nKUSHI TITLE SONG TELUGU\nMusic Composed, Arranged & Programmed by Hesham Abdul Wahab\nLyrics by Shiva Nirvana\nSung by Hesham Abdul Wahab\nChoreographer Brindha Master\n\nMusician Credits: \n\nSaaz & Oud: Tapas Roy\nBass Guitar: Sumesh Parameswar\nMridangam: D.A Srinivas \nStrings: Chennai Strings\n\nMusic Assistants: Suroor Musthafa & George Thomas PV\nArtist Co-ordination: K.D Vincent & Don Vincent\n\nSong Mixed and Mastered by\nEric Pillai (Future Sound Of Bombay)\n\nRecording Engineers:\nSuroor Musthafa  @HW Studio (Cochin)\nGeorge Thomas PV @HW Studio (Cochin) \nBiju James @UNO Records (Chennai)\nNaresh Mamindla @Jubilee10 Studios (Hyderabad)\nRakesh Mikky @Jubilee10 Studios (Hyderabad)\nMidhun Manoj @Soundtown Studios (Chennai)\nVishnu Shankar @Soundtown Studios (Chennai)\nRahul @Studio504 (Mumbai)\n\n\nAudio Recording Studios:\nHW Studio (Cochin)\nUNO Records (Chennai)\nJubilee10 Studios (Hyderabad)\nSoundtown Studios (Chennai) \nStudio504 (Mumbai)\n\nCast - Vijay Deverakonda, Samantha Ruth Prabhu, Jayaram, Sachin Khedakar, Murali Sharma, Lakshmi, Ali, Rohini, Vennela Kishore, Rahul Ramakrishna, Srikanth Iyengar and Saranya Pradeep\n\nTechnical Crew:\nMake Up : Basha\nCostumes : P.Venkat\nStylist: Rajesh\nProduction Executive: Denkala RamaKrishna \nProduction Controller: Shaik Shekshavali \nArt Directors : Uttara kumar Surisetty, Chandrika\nStunts : Peter Hein, V.Venkat \nChoreography: Choreography: Raju Sundaram, Brinda, Pony Verma\nP.R.O : GSK Media\nWriting Assistance : Naresh babu.P\nPublicity Designer: Kabilan\nCo-Director: Suresh kumar\nProduction Designer: Jayashree Lakshminarayanan\nExecutive Producer : Dinesh Narasimhan\nEditing : Prawin Pudi\nMusic : Hesham Abdul Wahab\nD.O.P : G.Murali\nC.E.O : Cherry\nMarketing : First Show\n\nD.I & SOUND MIX : ANNAPURNA STUDIOS \nVFX : MATRIX\nPRODUCERS : NAVEEN YERNENI RAVI SHANKAR YELAMANCHILI \nSTORY - SCREENPLAY - DIALOGUES - DIRECTION : SHIVA NIRVANA\n\nLabel: Saregama India Limited, A RPSG Group Company\n\nTo buy Carvaan, visit https://www.saregama.com/carvaan/telugu\nTo buy virus free original tracks, visit  https://www.saregama.com/musicstore\nFollow us on: YouTube:https://www.youtube.com/channel/saregamatelugu\nFacebook: http://www.facebook.com/Saregamatelugu\nTwitter: https://twitter.com/saregamasouth​​\n\n#KushiTitleSong #VijayDeverakonda #Samantha #SaregamaTelugu",
        },
        defaultAudioLanguage: "te",
      },
      contentDetails: {
        duration: "PT24S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1041137",
        likeCount: "47423",
        favoriteCount: "0",
        commentCount: "675",
      },
    },
    {
      kind: "youtube#video",
      etag: "YNF4MibXn0dodSTjTx0xKlyuE1E",
      id: "YCWeW6WKXHE",
      snippet: {
        publishedAt: "2023-07-26T02:30:15Z",
        channelId: "UCjvgGbPPn-FgYeguc5nxG4A",
        title: "Highway Pe Accident Hogya 😭 Bach Gaye",
        description:
          "Follow me on Instagram- https://www.instagram.com/souravjoshivlogs/?hl=en\n \nI hope you enjoyed this video\n\nhit likes.\nAnd do subscribe to my channel\n\nThank you so much for watching\n\ngod bless you all.\nlots of  ❤️\n\n( For Collaboration - officialsouravjoshivlogs@gmail.com",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/YCWeW6WKXHE/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/YCWeW6WKXHE/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/YCWeW6WKXHE/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/YCWeW6WKXHE/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/YCWeW6WKXHE/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Sourav Joshi Vlogs",
        tags: [
          "dubai vlogs",
          "traveling to dubai",
          "sourav joshi",
          "sourav joshi vlogs",
          "travel vlogs",
          "family vlogs",
          "toys",
          "action figers",
          "spider man",
          "piyush joshi",
          "piyush joshi vlogs",
          "thar vlog",
          "offroading with thar",
          "Highway Pe Accident",
          "fortuner ka accident",
          "fortuner accident video",
          "highway accident",
          "highway accident video",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "Highway Pe Accident Hogya 😭 Bach Gaye",
          description:
            "Follow me on Instagram- https://www.instagram.com/souravjoshivlogs/?hl=en\n \nI hope you enjoyed this video\n\nhit likes.\nAnd do subscribe to my channel\n\nThank you so much for watching\n\ngod bless you all.\nlots of  ❤️\n\n( For Collaboration - officialsouravjoshivlogs@gmail.com",
        },
      },
      contentDetails: {
        duration: "PT13M2S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "5984043",
        likeCount: "407324",
        favoriteCount: "0",
        commentCount: "12439",
      },
    },
    {
      kind: "youtube#video",
      etag: "alhyftS1gh_mja2RToTI-ACfo7M",
      id: "7pUMmpeNo18",
      snippet: {
        publishedAt: "2023-07-24T14:00:05Z",
        channelId: "UCUPD0jQo-EP0B1Nf4uzeIMA",
        title:
          'അശ്വിനും അരുണിനും "പത്തുലക്ഷം" നേടിക്കൊടുത്ത  the ever hit Bumber Skit 🔥 #ocicbcseason1',
        description:
          'അശ്വിനും അരുണിനും പത്തുലക്ഷം നേടിക്കൊടുത്ത  the ever hit "Bumber Skit"\n\nClick the link to watch this whole episode: http://surl.li/jkppl\n\nOruChiriIruChiriBumperChiriSeason1 Episode 515 | Watch on manoramaMAX\n\nOruChiriIruChiriBumperChiriSeason2 | Mon-Fri 9 PM | MazhavilManorama \n\nWatch OruChiriIruChiriBumperChiriSeason2 Episodes on the manoramaMAX app\n\n#OruChiriIruChiriBumperChiriSeason2 #Ocicbc #OruChiriIruChiriBumperChiri \n#MazhavilManorama #manoramaMAX #ComedyProgram #MazhavilManorama #MazhavilManorama #MazhavilRewinds\n\n\n► Subscribe Now: https://bit.ly/2UsOmyA  \n\n►  Visit manoramaMAX for full episodes: https://www.manoramamax.com \n\n► Click to install the manoramaMAX app: https://www.manoramamax.com/install\n\nFollow us on: \n\n► Facebook: https://facebook.com/mazhavilmanorama\n\n ► Instagram: http://instagram.com/mazhavilmanoramatv \n\n► Twitter: https://twitter.com/yourmazhavil',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/7pUMmpeNo18/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/7pUMmpeNo18/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/7pUMmpeNo18/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/7pUMmpeNo18/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/7pUMmpeNo18/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Mazhavil Manorama",
        tags: [
          "Mazhavil",
          "Manorama",
          "ManoramaMax",
          "oru chiri oru chiri bumper chiri",
          "oruchiriiruchiribumperchiriseason2",
          "oru chiri oru chiri bumper chiri manjupilla",
          "manjupilla",
          "nazeer sankranthi",
          "sabumon",
          "karthiksurya",
          "oru chiri oru chiri bumper chiri season 2",
          "oruchiriiruchiri",
          "oruchirilatest",
          "oruchiricomedy",
          "comedyprogram",
          "mazhaviolcomedy",
          "OruChiriIruChiriBumperChiriSeason2",
          "Ocicbc",
          "MazhavilManorama",
          "ComedyProgram",
          "comedy",
          "comedyskit",
          "mazhavilcomedy",
          "manoramaMAX",
          "10lakhskit",
          "tenlakhwinningskit",
          "aswinarun",
          "aswinaruntenlakh",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "ml",
        localized: {
          title:
            'അശ്വിനും അരുണിനും "പത്തുലക്ഷം" നേടിക്കൊടുത്ത  the ever hit Bumber Skit 🔥 #ocicbcseason1',
          description:
            'അശ്വിനും അരുണിനും പത്തുലക്ഷം നേടിക്കൊടുത്ത  the ever hit "Bumber Skit"\n\nClick the link to watch this whole episode: http://surl.li/jkppl\n\nOruChiriIruChiriBumperChiriSeason1 Episode 515 | Watch on manoramaMAX\n\nOruChiriIruChiriBumperChiriSeason2 | Mon-Fri 9 PM | MazhavilManorama \n\nWatch OruChiriIruChiriBumperChiriSeason2 Episodes on the manoramaMAX app\n\n#OruChiriIruChiriBumperChiriSeason2 #Ocicbc #OruChiriIruChiriBumperChiri \n#MazhavilManorama #manoramaMAX #ComedyProgram #MazhavilManorama #MazhavilManorama #MazhavilRewinds\n\n\n► Subscribe Now: https://bit.ly/2UsOmyA  \n\n►  Visit manoramaMAX for full episodes: https://www.manoramamax.com \n\n► Click to install the manoramaMAX app: https://www.manoramamax.com/install\n\nFollow us on: \n\n► Facebook: https://facebook.com/mazhavilmanorama\n\n ► Instagram: http://instagram.com/mazhavilmanoramatv \n\n► Twitter: https://twitter.com/yourmazhavil',
        },
        defaultAudioLanguage: "ml",
      },
      contentDetails: {
        duration: "PT14M30S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2770103",
        likeCount: "67090",
        favoriteCount: "0",
        commentCount: "1501",
      },
    },
    {
      kind: "youtube#video",
      etag: "7jS7bh4AoCBMZouXzk1Gn3FLwJs",
      id: "79URzxNZAh8",
      snippet: {
        publishedAt: "2023-07-27T07:00:04Z",
        channelId: "UC2zTRxJjjNYZpdXHk_blEHg",
        title:
          "Manchesterൽ നിന്നും നേരത്തെ തിരിച്ചെത്തി || ഒരു വലിയ വിശേഷം പറയാനുണ്ട്",
        description:
          "◆◆◆ Stay Connected With Me:- ◆◆◆\n ◆ YouTube: http://bit.ly/LekshmiNairVlogs \n ◆ Facebook Page: https://www.facebook.com/drlekshminairofficial\n ◆ Facebook Profile: https://www.facebook.com/lekshmi.nair.5070\n ◆ Insta: https://www.instagram.com/lekshminair20 \n ◆ Official Blog: https://www.lekshminair.com \n\n●●● For Business Enquiries, Contact●●●\n ◆ Email: contact@lekshminair.com\n ◆ WhatsApp: http://wa.me/919746969808\n ◆ Send Message/SMS (Only): (+91) 97469 69808 (Calls Disabled)\n\n◆◆ About Me ◆◆\nIt’s me Lekshmi Nair, a celebrity culinary expert. Cooking has always been my passion. Since my childhood, I loved experimenting and trying new dishes and recipes. This YouTube channel ‘#LekshmiNairVlogs’ is my latest venture to share my recipes with you and to be connected with you.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/79URzxNZAh8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/79URzxNZAh8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/79URzxNZAh8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/79URzxNZAh8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/79URzxNZAh8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Lekshmi Nair",
        tags: [
          "celebrity vlogs",
          "malayalam celebrity vlogs",
          "lekshmi nair vlogs",
          "trending celebrity vlogs",
          "pregnancy announcement",
          "pregnancy malayalam",
          "pregnancy journey",
          "good news",
          "lekshmi nair",
          "lakshmi nair",
          "trending",
          "malayalam youtube channel",
          "malayalam celebrity news",
          "anuradha p nair",
          "anuradha nair",
        ],
        categoryId: "26",
        liveBroadcastContent: "none",
        defaultLanguage: "ml",
        localized: {
          title:
            "Manchesterൽ നിന്നും നേരത്തെ തിരിച്ചെത്തി || ഒരു വലിയ വിശേഷം പറയാനുണ്ട്",
          description:
            "◆◆◆ Stay Connected With Me:- ◆◆◆\n ◆ YouTube: http://bit.ly/LekshmiNairVlogs \n ◆ Facebook Page: https://www.facebook.com/drlekshminairofficial\n ◆ Facebook Profile: https://www.facebook.com/lekshmi.nair.5070\n ◆ Insta: https://www.instagram.com/lekshminair20 \n ◆ Official Blog: https://www.lekshminair.com \n\n●●● For Business Enquiries, Contact●●●\n ◆ Email: contact@lekshminair.com\n ◆ WhatsApp: http://wa.me/919746969808\n ◆ Send Message/SMS (Only): (+91) 97469 69808 (Calls Disabled)\n\n◆◆ About Me ◆◆\nIt’s me Lekshmi Nair, a celebrity culinary expert. Cooking has always been my passion. Since my childhood, I loved experimenting and trying new dishes and recipes. This YouTube channel ‘#LekshmiNairVlogs’ is my latest venture to share my recipes with you and to be connected with you.",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT9M48S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "289214",
        likeCount: "6723",
        favoriteCount: "0",
        commentCount: "1537",
      },
    },
    {
      kind: "youtube#video",
      etag: "ZQGfkMugXBONzbZZroKGfBEmnfo",
      id: "4fw5y1JLYtM",
      snippet: {
        publishedAt: "2023-07-26T14:06:09Z",
        channelId: "UCWKzBXU_5jgyXwmlj04H2dg",
        title:
          "USTAAD Theatrical Trailer | Simha Koduri | Kavya Kalyanram | Phanideep | Vaaraahi Chalana Chitram",
        description:
          "The heartwarming #UstaadTrailer is out now. \n\nJoin the thrilling ride and witness the inspiring journey of a man who strives to reach great heights.\n\nUSTAAD movie *ing Sri Simha Koduri, Kavya Kalyanram, Gautham Vasudev Menon, Anu Hasan, Ravindra Vijay, Venkatesh Maha, Ravi Siva Teja, Sai Kiran Yedida. \n\n#Ustaad #SriSimhaKoduri #VaaraahiChalanaChitram #SaiKorrapati #Phanideep #GauthamVasudevMenon # AnuHasan #RavindraVijay #RakeshReddygaddam #RajaniKorrapati #HimankhReddyduvvuru \n\nCREW :\nWriter & Director - Phanideep\nProducers - Rajani Korrapati - Rakesh Reddy Gaddam - Himank Reddy Duvvuru\nCinematography - Pavan Kumar Pappula\nMusic - Akeeva B \nEditor - Carthic Cuts \nProduction Designer - Aravind Mule\nSound Design - Ashwin Rajasekhar \nCostume Designer - Priyanka Veeraboina\nVFX Supervisor - Sunil Raju Chinta\nLyrics - Anantha Sriram, Rahman, Lakshmi Priyanka\nLine Producers - Prajnay Konigari - Rajesh Reddy Gaddam\nPublicity Designer - RC Designs\nDigital Partner - Silly Monks \nMarketing - Walls & Trends\nPRO - Vamsi Kaka\n\nDI : Sri Sarathi Studios Pvt Ltd \nColorist : Vishnu Vardhan K\n\nMusic composed, programmed & produced by Akeeva B\nSingers: Arjun, Saketh, Satvik, Pavani Vasa, Soujanya Bhagavatula, Tejaswini \nElectric Guitar: Bruce Lee\nRecorded at 1.618 Sound (Siddipet), Moksha Studio (Hyderabad)\nRecording engineer: Venkat (Moksha Studio)\n\nSound Mix: \nAnnapurna Studios \nMix Engineer: Kannan Ganpat\nLine Producer : Sandeep\n\nSubtitles - Gayatri chaganti\n\nFor More Updates :\nSubscribe @ https://www.youtube.com/user/vaaraahi?sub_confirmation=1 \nLike @ https://www.facebook.com/Vaaraahi\nFollow @ https://twitter.com/VaaraahiCC",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/4fw5y1JLYtM/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/4fw5y1JLYtM/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/4fw5y1JLYtM/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/4fw5y1JLYtM/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/4fw5y1JLYtM/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Vaaraahi Chalana Chitram",
        tags: [
          "USTAAD",
          "Ustaad",
          "ustaad trailer",
          "ustaad movie",
          "ustaad trailer hd",
          "sri simha ustaad trailer",
          "sr simha ustaad movie",
          "ustaad sri simha movie",
          "kavya kalyanram",
          "kavya kalyanram movies",
          "gautham vasudev menon",
          "phanideep director phani deep",
          "latest telugu movies",
          "latest trailers",
          "vaaraahi chalana chitram",
          "ustaad movie songs",
          "ustadd movie trailer",
          "telugu trailer",
          "ustaad bhagat singh",
          "pawan kalyan ustaad bhagat singh",
          "sri simha movies",
          "ustaad",
          "ustad bhagat singh trailer",
          "bro trailer",
        ],
        categoryId: "1",
        liveBroadcastContent: "none",
        localized: {
          title:
            "USTAAD Theatrical Trailer | Simha Koduri | Kavya Kalyanram | Phanideep | Vaaraahi Chalana Chitram",
          description:
            "The heartwarming #UstaadTrailer is out now. \n\nJoin the thrilling ride and witness the inspiring journey of a man who strives to reach great heights.\n\nUSTAAD movie *ing Sri Simha Koduri, Kavya Kalyanram, Gautham Vasudev Menon, Anu Hasan, Ravindra Vijay, Venkatesh Maha, Ravi Siva Teja, Sai Kiran Yedida. \n\n#Ustaad #SriSimhaKoduri #VaaraahiChalanaChitram #SaiKorrapati #Phanideep #GauthamVasudevMenon # AnuHasan #RavindraVijay #RakeshReddygaddam #RajaniKorrapati #HimankhReddyduvvuru \n\nCREW :\nWriter & Director - Phanideep\nProducers - Rajani Korrapati - Rakesh Reddy Gaddam - Himank Reddy Duvvuru\nCinematography - Pavan Kumar Pappula\nMusic - Akeeva B \nEditor - Carthic Cuts \nProduction Designer - Aravind Mule\nSound Design - Ashwin Rajasekhar \nCostume Designer - Priyanka Veeraboina\nVFX Supervisor - Sunil Raju Chinta\nLyrics - Anantha Sriram, Rahman, Lakshmi Priyanka\nLine Producers - Prajnay Konigari - Rajesh Reddy Gaddam\nPublicity Designer - RC Designs\nDigital Partner - Silly Monks \nMarketing - Walls & Trends\nPRO - Vamsi Kaka\n\nDI : Sri Sarathi Studios Pvt Ltd \nColorist : Vishnu Vardhan K\n\nMusic composed, programmed & produced by Akeeva B\nSingers: Arjun, Saketh, Satvik, Pavani Vasa, Soujanya Bhagavatula, Tejaswini \nElectric Guitar: Bruce Lee\nRecorded at 1.618 Sound (Siddipet), Moksha Studio (Hyderabad)\nRecording engineer: Venkat (Moksha Studio)\n\nSound Mix: \nAnnapurna Studios \nMix Engineer: Kannan Ganpat\nLine Producer : Sandeep\n\nSubtitles - Gayatri chaganti\n\nFor More Updates :\nSubscribe @ https://www.youtube.com/user/vaaraahi?sub_confirmation=1 \nLike @ https://www.facebook.com/Vaaraahi\nFollow @ https://twitter.com/VaaraahiCC",
        },
        defaultAudioLanguage: "en-US",
      },
      contentDetails: {
        duration: "PT2M24S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2245219",
        likeCount: "26682",
        favoriteCount: "0",
        commentCount: "426",
      },
    },
    {
      kind: "youtube#video",
      etag: "9sBVRXdPcfAJkLg88GT6gRHxBo4",
      id: "g3MIXos8_B8",
      snippet: {
        publishedAt: "2023-07-28T02:56:30Z",
        channelId: "UCT-teXvffuQY8-XFqjHRnGQ",
        title: "Bro Movie Review | Cinemapicha",
        description: "Bro Movie Review",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/g3MIXos8_B8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/g3MIXos8_B8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/g3MIXos8_B8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/g3MIXos8_B8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/g3MIXos8_B8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Cinemapicha",
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "Bro Movie Review | Cinemapicha",
          description: "Bro Movie Review",
        },
        defaultAudioLanguage: "te",
      },
      contentDetails: {
        duration: "PT5M45S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "129186",
        likeCount: "4563",
        favoriteCount: "0",
        commentCount: "448",
      },
    },
    {
      kind: "youtube#video",
      etag: "MtD1egXmKNEC-nvvCHa_f0Tk2F8",
      id: "hguZf5LmRc0",
      snippet: {
        publishedAt: "2023-07-24T12:30:23Z",
        channelId: "UC0zXnLIFedO97pFsyMxZcFg",
        title: "BaBu or Papa | the mridul | Pragati | Nitin",
        description:
          "Hello Doston👋🏻🥰\n“ आप हँसते रहो, हम हँसाते रहेंगे “ \n\nFollow MriDul on instagram ~ https://www.instagram.com/themridul_/\n\nFollow Nitin on instagram ~ \nhttps://www.instagram.com/i.am.nitin_/\n \nBaBu or Papa | the mridul | Pragati | Nitin\n\nSCRIPT ~  The MriDul \nDIRECTED BY ~ Nitin, MriDul\nSHOOT & EDIT ~ Maan Gujjar \nASSISTANT DIRECTOR ~ Ujjwal \nMUSIC ~ Maan Gujjar \nTHUMBNAIL ~ Raj Sharma\n\nCAST ( Male )                  CAST ( Female)\nMriDul                                Riya\nNitin                                   Shilpa\nUjjwal ( Mastani )   \nAarav ( Bakra)      \nSmack that ( Papa )         \nRamdhan\nBharam \n\nSpecial Thanks To You All Supporter \nPLEASE SUBSCRIBE ❤️ राम राम जी",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/hguZf5LmRc0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/hguZf5LmRc0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/hguZf5LmRc0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/hguZf5LmRc0/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/hguZf5LmRc0/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "The MriDul",
        tags: [
          "the mridul",
          "the mridul new video",
          "mridul nitin",
          "pragati new video",
          "pragati",
          "mridul pragati",
          "nitin mridul",
          "mastani ki comedy",
          "new comedy video",
          "comedy",
          "babu ki video",
          "setting se meeting",
          "setting in the house",
          "best comedy",
          "trending video",
          "mridul new video",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        defaultLanguage: "hi",
        localized: {
          title: "BaBu or Papa | the mridul | Pragati | Nitin",
          description:
            "Hello Doston👋🏻🥰\n“ आप हँसते रहो, हम हँसाते रहेंगे “ \n\nFollow MriDul on instagram ~ https://www.instagram.com/themridul_/\n\nFollow Nitin on instagram ~ \nhttps://www.instagram.com/i.am.nitin_/\n \nBaBu or Papa | the mridul | Pragati | Nitin\n\nSCRIPT ~  The MriDul \nDIRECTED BY ~ Nitin, MriDul\nSHOOT & EDIT ~ Maan Gujjar \nASSISTANT DIRECTOR ~ Ujjwal \nMUSIC ~ Maan Gujjar \nTHUMBNAIL ~ Raj Sharma\n\nCAST ( Male )                  CAST ( Female)\nMriDul                                Riya\nNitin                                   Shilpa\nUjjwal ( Mastani )   \nAarav ( Bakra)      \nSmack that ( Papa )         \nRamdhan\nBharam \n\nSpecial Thanks To You All Supporter \nPLEASE SUBSCRIBE ❤️ राम राम जी",
        },
        defaultAudioLanguage: "hi",
      },
      contentDetails: {
        duration: "PT13M11S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "3397776",
        likeCount: "156130",
        favoriteCount: "0",
        commentCount: "6453",
      },
    },
    {
      kind: "youtube#video",
      etag: "e6H1MxPLatbmWybEQdm31ha8w84",
      id: "oBlxdr1KbEA",
      snippet: {
        publishedAt: "2023-07-22T18:29:10Z",
        channelId: "UCzee67JnEcuvjErRyWP3GpQ",
        title:
          "Kanguva - Glimpse | Suriya, Disha Patani | Devi Sri Prasad | Siva | Studio Green | UV Creations",
        description:
          "Khiladi : 1300% bonus on first deposit-https://bit.ly/3Dmrzwq\n\nStudio Green K.E. Gnanavelraja in association with UV Creations Vamsi - Pramod presents\nSiva Directorial 'Kanguva'. Team unveils the promo teaser on a grand scale in 6 languages.\n\nMovie Credits:\nMovie Credits: Starring : Suriya, Disha Patani & Others\nDirected by : Siva\nDirector of Photography : Vetri Palanisamy\nMusic : 'Rockstar' Devi Sri Prasad\nArt : Milan\nEditor: Nishad Yusuf\nAction : Supreme Sundar\nDialogues : Madan Karky\nWriter : Adi Narayana\nLyrics : Viveka - Madan Karky\nRecording Engineer-Lawrence Vishnu Sound and Vision Studios Pvt Ltd\nChief Co Director : R.Rajasekar\nCostume Designer : Anu Vardhan (Suriya) Dhatsha Pillai\nCostumes : Rajan\nMakeup : Serina (Suriya) , Kuppusamy\nSpecial Make up - Ranjith Ambadi\nADR: Vignesh Guru\nChoreography : Shobi – Prem Rakshith\nSound Design : T Udhayakumar\nStills : C.H. Balu Publicity Design : Kabilan Chelliah\nColorist: K S Rajasekaran (Igene)\nVFX : Harihara Suthan\nCo-Directors : Hemachandraprabhu - Thirumalai\nAssociate Director : S Kannan – R Thilipan- Rajaram – S Nagendran\nProduction Controller : R.S. Sureshmaniyan\nProduction Executive : Rama Doss\nProduction Co-ordination : EV Dinesh Kumar\nPRO : Suresh Chandra & Rekha D’One\nDigital Partner : Mango Mass Media Pvt Ltd\nDigital Promotions: Digitally & Whacked Out Media\nCreative Promotions: BeatRoute\nExecutive Producer: A.G. Raja\nStudio Green CEO G. Dhananjeyan\nCo-Producer: Neha Gnanavelraja\nProduced by : K.E. Gnanavelraja | Vamsi-Pramod\nBanner : Studio Green | UV Creations\n\nKhiladi : 1300% bonus on first deposit-https://bit.ly/3Dmrzwq\n\nKannada Language\nVocals -Devi Sri Prasad, Santosh Venky\nLyricist - Varadaraj Chikkaballapura\nSound and Vision Studios Pvt Ltd \n\nTelugu Language\nVocals - Devi Sri Prasad, Hemachandra\nLyricist- Sahiti Cherukupally\nSound and Vision Studios Pvt.Ltd \n\nMalayalam Language\nVocals - Devi Sri Prasad, Manoj Mathew\nLyricist - Mankompu Gopalakrishnan\nRecording Engineer - Jubin Raj\nSound and Vision Studios Pvt Ltd \n\nHindi Language\nVocals - Devi Sri Prasad, Ninad Kamat\nLyricist - Vimal Kashyap\nVocal Supervisor- Ratnesh Bhagat\nRecording Engineer - Vipul Bhirwandekar\nSound and Vision Studios Pvt Ltd \n\nEnglish Language\nVocals - Devi Sri Prasad, John E\nLyricist - Sidd Coutto\nVocal Supervisor - Sunayana Sarkar\nSound and Vision Studios Pvt Ltd\n\nTamil Language\nVocal - Devi Sri Prasad, Arunraja Kamaraja\nLyricist-Madhan Karky\nRecording Engineer-Lawrence Vishnu\nSound and  Vision Studios Pvt Ltd\n\nLabel: Saregama India Limited, A RPSG Group Company\n\n \nTo buy Carvaan, visit https://www.saregama.com/carvaan/tamil\nTo buy virus free original tracks, visit  https://www.saregama.com/musicstore\nFollow us on: YouTube: https://www.youtube.com/user/Saregamatamil\nFacebook: http://www.facebook.com/Saregamatamil\nTwitter: https://twitter.com/saregamasouth​​\n\n#Kanguva #Suriya #DishaPatani #Suriya42 #SaregamaTamil",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/oBlxdr1KbEA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/oBlxdr1KbEA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/oBlxdr1KbEA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/oBlxdr1KbEA/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/oBlxdr1KbEA/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Saregama Tamil",
        tags: [
          "Kanguva",
          "Kanguva Glimpse",
          "Kanguva Tamil movie",
          "Suriya 42",
          "Suriya",
          "Suriya movies",
          "Suriya Kanguva",
          "Disha Patani",
          "Disha Patani movies",
          "Kanguva Promo",
          "Kanguva Teaser",
          "Kanguva Trailer",
          "Kanguva movie",
          "actor suriya",
          "Suriya birthday special",
          "Devi Sri Prasad",
          "Devi Sri Prasad songs",
          "Tamil movies",
          "Tamil Films",
          "Tamil movies Latest",
          "Latest Tamil Films",
          "Tamil Films 2023",
          "Trending videos",
          "tamil trailers",
          "Studio Green",
        ],
        categoryId: "1",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title:
            "Kanguva - Glimpse | Suriya, Disha Patani | Devi Sri Prasad | Siva | Studio Green | UV Creations",
          description:
            "Khiladi : 1300% bonus on first deposit-https://bit.ly/3Dmrzwq\n\nStudio Green K.E. Gnanavelraja in association with UV Creations Vamsi - Pramod presents\nSiva Directorial 'Kanguva'. Team unveils the promo teaser on a grand scale in 6 languages.\n\nMovie Credits:\nMovie Credits: Starring : Suriya, Disha Patani & Others\nDirected by : Siva\nDirector of Photography : Vetri Palanisamy\nMusic : 'Rockstar' Devi Sri Prasad\nArt : Milan\nEditor: Nishad Yusuf\nAction : Supreme Sundar\nDialogues : Madan Karky\nWriter : Adi Narayana\nLyrics : Viveka - Madan Karky\nRecording Engineer-Lawrence Vishnu Sound and Vision Studios Pvt Ltd\nChief Co Director : R.Rajasekar\nCostume Designer : Anu Vardhan (Suriya) Dhatsha Pillai\nCostumes : Rajan\nMakeup : Serina (Suriya) , Kuppusamy\nSpecial Make up - Ranjith Ambadi\nADR: Vignesh Guru\nChoreography : Shobi – Prem Rakshith\nSound Design : T Udhayakumar\nStills : C.H. Balu Publicity Design : Kabilan Chelliah\nColorist: K S Rajasekaran (Igene)\nVFX : Harihara Suthan\nCo-Directors : Hemachandraprabhu - Thirumalai\nAssociate Director : S Kannan – R Thilipan- Rajaram – S Nagendran\nProduction Controller : R.S. Sureshmaniyan\nProduction Executive : Rama Doss\nProduction Co-ordination : EV Dinesh Kumar\nPRO : Suresh Chandra & Rekha D’One\nDigital Partner : Mango Mass Media Pvt Ltd\nDigital Promotions: Digitally & Whacked Out Media\nCreative Promotions: BeatRoute\nExecutive Producer: A.G. Raja\nStudio Green CEO G. Dhananjeyan\nCo-Producer: Neha Gnanavelraja\nProduced by : K.E. Gnanavelraja | Vamsi-Pramod\nBanner : Studio Green | UV Creations\n\nKhiladi : 1300% bonus on first deposit-https://bit.ly/3Dmrzwq\n\nKannada Language\nVocals -Devi Sri Prasad, Santosh Venky\nLyricist - Varadaraj Chikkaballapura\nSound and Vision Studios Pvt Ltd \n\nTelugu Language\nVocals - Devi Sri Prasad, Hemachandra\nLyricist- Sahiti Cherukupally\nSound and Vision Studios Pvt.Ltd \n\nMalayalam Language\nVocals - Devi Sri Prasad, Manoj Mathew\nLyricist - Mankompu Gopalakrishnan\nRecording Engineer - Jubin Raj\nSound and Vision Studios Pvt Ltd \n\nHindi Language\nVocals - Devi Sri Prasad, Ninad Kamat\nLyricist - Vimal Kashyap\nVocal Supervisor- Ratnesh Bhagat\nRecording Engineer - Vipul Bhirwandekar\nSound and Vision Studios Pvt Ltd \n\nEnglish Language\nVocals - Devi Sri Prasad, John E\nLyricist - Sidd Coutto\nVocal Supervisor - Sunayana Sarkar\nSound and Vision Studios Pvt Ltd\n\nTamil Language\nVocal - Devi Sri Prasad, Arunraja Kamaraja\nLyricist-Madhan Karky\nRecording Engineer-Lawrence Vishnu\nSound and  Vision Studios Pvt Ltd\n\nLabel: Saregama India Limited, A RPSG Group Company\n\n \nTo buy Carvaan, visit https://www.saregama.com/carvaan/tamil\nTo buy virus free original tracks, visit  https://www.saregama.com/musicstore\nFollow us on: YouTube: https://www.youtube.com/user/Saregamatamil\nFacebook: http://www.facebook.com/Saregamatamil\nTwitter: https://twitter.com/saregamasouth​​\n\n#Kanguva #Suriya #DishaPatani #Suriya42 #SaregamaTamil",
        },
        defaultAudioLanguage: "ta",
      },
      contentDetails: {
        duration: "PT2M22S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "31242995",
        likeCount: "860194",
        favoriteCount: "0",
        commentCount: "49036",
      },
    },
    {
      kind: "youtube#video",
      etag: "uwhaL4Fr_WoQ7mpoMxIVPEA-q8k",
      id: "3d9i5s-swXQ",
      snippet: {
        publishedAt: "2023-07-27T00:45:00Z",
        channelId: "UCJfeUWkrU4JwIJfP-usd-_w",
        title:
          "#Video | हिरउआ बम | #Khesari Lal Yadav | Hirauwa Bam | #Shilpi Raj | Latest Bol Bam Song 2023",
        description:
          "Subscribe Now:-  https://goo.gl/j2d2Th\n\n#Video | हिरउआ बम | #Khesari Lal Yadav | Hirauwa Bam | #Shilpi Raj | Latest Bol Bam Song 2023\n\n\nIf you like Bhojpuri song, Bhojpuri full film and bhojpuri movie songs, Subscribe Now:- https://goo.gl/j2d2Th\n\nVisit our website to download our songs and videos: http://www.khesarientertainment.in\n\nLike Us On Facebook - https://www.facebook.com/khesarimusicworld/\n\nAlbum :- हिरउआ बम\nSong :- Hirahua Bam\nSinger :- Khesari Lal Yadav, Shilpi Raj\nLyrics :- Mukesh Yadav\nMusic :- Vikas Yadav\nVideo Director :- Ashish Satyarthi\nPoster :- Arun Dev \nDigital Managed By :- Global Music Junction Pvt. Ltd.\nCompany/Label - Khesari Music World\n\n#khesari #shilpi #bolbam #khesarimusicworld #video",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/3d9i5s-swXQ/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/3d9i5s-swXQ/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/3d9i5s-swXQ/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/3d9i5s-swXQ/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/3d9i5s-swXQ/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Khesari Music World",
        tags: [
          "Hirauwa Bam Song",
          "Khesari Lal Yadav",
          "khesari lal ka bolbam gana",
          "khesari lal yadav new song",
          "Hirauwa Bam video",
          "Hirauwa Bam ka video",
          "shilpi raj",
          "khesari lal bol bam song",
          "khesari lal yadav shilpi raj",
          "khesari lal new kanwar geet",
          "khesari lal yadav video",
          "khesari lal bolbam song 2023",
          "khesari lal video song 2023",
          "#khesari lal ke gana",
          "khesari bol bam song",
          "khesari lal bhojpuri video songs",
          "Khesari Lal Yadav New Bolbam Gaana",
          "shilpi raj bol bam",
          "हिरउआ बम",
          "khesari music world",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        defaultLanguage: "hi",
        localized: {
          title:
            "#Video | हिरउआ बम | #Khesari Lal Yadav | Hirauwa Bam | #Shilpi Raj | Latest Bol Bam Song 2023",
          description:
            "Subscribe Now:-  https://goo.gl/j2d2Th\n\n#Video | हिरउआ बम | #Khesari Lal Yadav | Hirauwa Bam | #Shilpi Raj | Latest Bol Bam Song 2023\n\n\nIf you like Bhojpuri song, Bhojpuri full film and bhojpuri movie songs, Subscribe Now:- https://goo.gl/j2d2Th\n\nVisit our website to download our songs and videos: http://www.khesarientertainment.in\n\nLike Us On Facebook - https://www.facebook.com/khesarimusicworld/\n\nAlbum :- हिरउआ बम\nSong :- Hirahua Bam\nSinger :- Khesari Lal Yadav, Shilpi Raj\nLyrics :- Mukesh Yadav\nMusic :- Vikas Yadav\nVideo Director :- Ashish Satyarthi\nPoster :- Arun Dev \nDigital Managed By :- Global Music Junction Pvt. Ltd.\nCompany/Label - Khesari Music World\n\n#khesari #shilpi #bolbam #khesarimusicworld #video",
        },
        defaultAudioLanguage: "bh",
      },
      contentDetails: {
        duration: "PT3M21S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "833202",
        likeCount: "98299",
        favoriteCount: "0",
        commentCount: "15977",
      },
    },
    {
      kind: "youtube#video",
      etag: "8i--IMiJfmshasjuQgfp3de-kqM",
      id: "1HfdF5xnnfw",
      snippet: {
        publishedAt: "2023-07-27T14:30:00Z",
        channelId: "UCUw8vQF-X7CJqdVpxBYcavQ",
        title: "Kande Pohe - Kothrud VS Sangli | @gsteaindia | #BhaDiPa",
        description:
          "#Kothrud #Sangli #kandepohe \n\nWhen a Sangli guy met a Punekar girl! They will debate about the food and culture? Our beloved Kothrud girl is all set to try her luck with a hardcore Sanglikar. But this time she is clean bowled by his word game? Let’s enjoy this witty and sarcastic banter together. And for such content subscribe to BhaDiPa. \n\nDo you need a great refresher for your mood and mind? Then GS Tea is the solution for you. It promises the tasteful tea straightly bought from Assam. Click on the link below for more information : http://amzn.to/3mAYAAx\nFacebook : https://www.facebook.com/gsteabrand?mibextid=LQQJ4d\nInstagram: https://instagram.com/gsteaindia?igshid=MzRlODBiNWFlZA==\nYoutube : https://www.youtube.com/@gstea-gsbrands5951\nWebsite : https://www.gsbrands.com/\n\nJoin this channel to get access to perks:\nhttps://www.youtube.com/channel/UCUw8vQF-X7CJqdVpxBYcavQ/join\n\nSubscribe to BhaDiPa to get alerts on our new videos! शास्त्र असते ते ! \nNEW MERCH!! BhaDiPa Stickers, Mugs, T-Shirts: https://bhadipa.merchgarage.com\n\nAll under one roof! https://bhadipa.com/ for more videos and events!\nhttps://www.facebook.com/BhaDiPa\nhttps://www.twitter.com/BhaDiPa\nhttps://www.instagram.com/BhaDiPa\n\nCast :\nLeena Bhagwat\nBhagyashree Limaye\nRamesh Wani\nMandar Mokashi\n\n\nCredit List:\nWriter - Sumit Patil\nDirector - Akshay Nar\nCinematographer & CC - Bhagyesh Rajeshirke\nCreative Producer - Sarang Sathaye \nEditor - Shreyash Ballal\nSound - Sunny\nAssistant Director - Sarthak Chirnerkar                                                                                                                                                  Executive Producer - Narendra Singh                                                                                                                                                  \nProduction Head - Kedar Naidu                                                                                                                                                            Production Manager - Mangesh Jadhav  \nProduction Coordinator - Akshay Gopal\nCreatives - Aniket Jadhav, Nadeem Khan\nSpot - Ekendra Singh\nSales and Brand Solutions Head - Swanand Tendulkar\nSales Executive - Shilpa Shetye\nSales Associate - Chinmay Jadhav\nSocial Media Team - Prachi Bagwe,\nTejas Desai, Vaibhavi Torde\nSubtitles - Amey Rane",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/1HfdF5xnnfw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/1HfdF5xnnfw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/1HfdF5xnnfw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/1HfdF5xnnfw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/1HfdF5xnnfw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Bharatiya Digital Party",
        tags: [
          "bharatiya digital party",
          "bhadipa latest",
          "marathi web series",
          "kandepohe",
          "kothrud",
          "sangli",
          "pune",
          "leena bhagwat",
          "Kothrud vs Sangli",
          "Bhagyashree limaye",
          "comedy",
          "punekar parents",
          "leena bhagwat fu bai fu",
          "maharashtra",
          "sangli mh 10",
          "sangli city tour",
          "Meeting For Arrange Marriage",
          "maharashtra politics",
          "majhi maina",
          "na andaz kuthla",
          "berojgar",
          "sai tamhankar",
          "tasgaon",
          "sanglikar",
          "annabhau sathe",
          "smriti mandana",
          "every punekar",
          "marathi",
        ],
        categoryId: "23",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "Kande Pohe - Kothrud VS Sangli | @gsteaindia | #BhaDiPa",
          description:
            "#Kothrud #Sangli #kandepohe \n\nWhen a Sangli guy met a Punekar girl! They will debate about the food and culture? Our beloved Kothrud girl is all set to try her luck with a hardcore Sanglikar. But this time she is clean bowled by his word game? Let’s enjoy this witty and sarcastic banter together. And for such content subscribe to BhaDiPa. \n\nDo you need a great refresher for your mood and mind? Then GS Tea is the solution for you. It promises the tasteful tea straightly bought from Assam. Click on the link below for more information : http://amzn.to/3mAYAAx\nFacebook : https://www.facebook.com/gsteabrand?mibextid=LQQJ4d\nInstagram: https://instagram.com/gsteaindia?igshid=MzRlODBiNWFlZA==\nYoutube : https://www.youtube.com/@gstea-gsbrands5951\nWebsite : https://www.gsbrands.com/\n\nJoin this channel to get access to perks:\nhttps://www.youtube.com/channel/UCUw8vQF-X7CJqdVpxBYcavQ/join\n\nSubscribe to BhaDiPa to get alerts on our new videos! शास्त्र असते ते ! \nNEW MERCH!! BhaDiPa Stickers, Mugs, T-Shirts: https://bhadipa.merchgarage.com\n\nAll under one roof! https://bhadipa.com/ for more videos and events!\nhttps://www.facebook.com/BhaDiPa\nhttps://www.twitter.com/BhaDiPa\nhttps://www.instagram.com/BhaDiPa\n\nCast :\nLeena Bhagwat\nBhagyashree Limaye\nRamesh Wani\nMandar Mokashi\n\n\nCredit List:\nWriter - Sumit Patil\nDirector - Akshay Nar\nCinematographer & CC - Bhagyesh Rajeshirke\nCreative Producer - Sarang Sathaye \nEditor - Shreyash Ballal\nSound - Sunny\nAssistant Director - Sarthak Chirnerkar                                                                                                                                                  Executive Producer - Narendra Singh                                                                                                                                                  \nProduction Head - Kedar Naidu                                                                                                                                                            Production Manager - Mangesh Jadhav  \nProduction Coordinator - Akshay Gopal\nCreatives - Aniket Jadhav, Nadeem Khan\nSpot - Ekendra Singh\nSales and Brand Solutions Head - Swanand Tendulkar\nSales Executive - Shilpa Shetye\nSales Associate - Chinmay Jadhav\nSocial Media Team - Prachi Bagwe,\nTejas Desai, Vaibhavi Torde\nSubtitles - Amey Rane",
        },
        defaultAudioLanguage: "mr",
      },
      contentDetails: {
        duration: "PT12M28S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "262605",
        likeCount: "10884",
        favoriteCount: "0",
        commentCount: "1833",
      },
    },
    {
      kind: "youtube#video",
      etag: "zX9p8mMPNUdlrsAIe7dF_KJXVAU",
      id: "lQTcp3qbvFU",
      snippet: {
        publishedAt: "2023-07-25T14:12:53Z",
        channelId: "UCk3JZr7eS3pg5AGEvBdEvFg",
        title:
          "1000 BIG SIZE CRABS | Big Blue Crab Fry Recipe Cooking in Village | Seafood Recipe | Crab Recipe",
        description:
          "Today in our village, we cook big size blue crabs by making delicious crab fry recipe. Usually, crabs are delicious even when cooking without adding any masala and spices. But we add some traditional masala, and it's fried in Traditional gingelly oil so that the taste and aroma are more delicious!",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/lQTcp3qbvFU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/lQTcp3qbvFU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/lQTcp3qbvFU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/lQTcp3qbvFU/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/lQTcp3qbvFU/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Village Cooking Channel",
        tags: ["crab recipe", "seafood", "crab", "crab fry", "blue crab"],
        categoryId: "26",
        liveBroadcastContent: "none",
        localized: {
          title:
            "1000 BIG SIZE CRABS | Big Blue Crab Fry Recipe Cooking in Village | Seafood Recipe | Crab Recipe",
          description:
            "Today in our village, we cook big size blue crabs by making delicious crab fry recipe. Usually, crabs are delicious even when cooking without adding any masala and spices. But we add some traditional masala, and it's fried in Traditional gingelly oil so that the taste and aroma are more delicious!",
        },
        defaultAudioLanguage: "en-US",
      },
      contentDetails: {
        duration: "PT8M31S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "4178279",
        likeCount: "120246",
        favoriteCount: "0",
        commentCount: "3190",
      },
    },
  ],
  nextPageToken: "CBQQAA",
  pageInfo: {
    totalResults: 190,
    resultsPerPage: 20,
  },
};
